/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewo;

import Controllero.*;
import Modelo.*;
import Viewo.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class frmEditSol extends javax.swing.JFrame {

    /**
     * Creates new form frmEditSol
     */
    public frmEditSol() {
        initComponents();
        this.setLocationRelativeTo(null); 
        getRootPane().setDefaultButton(btnEditar); 
    }
    
    Funcionario f = new Funcionario();
    Solicitante s = new Solicitante(); 
    Tecnico t = new Tecnico();
    ctrlCadFuncionario ccf = new ctrlCadFuncionario();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tNome = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tLogin = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tMatricula = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tRamal = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tSetor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tAndar = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 510, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Editar perfil");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 630, 1));

        tNome.setForeground(new java.awt.Color(51, 51, 51));
        tNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tNomeFocusGained(evt);
            }
        });
        getContentPane().add(tNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 263, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nome");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        tEmail.setForeground(new java.awt.Color(51, 51, 51));
        tEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 263, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("E-mail");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        tSenha.setForeground(new java.awt.Color(51, 51, 51));
        tSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSenhaFocusGained(evt);
            }
        });
        getContentPane().add(tSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 263, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Senha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        tLogin.setForeground(new java.awt.Color(51, 51, 51));
        tLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tLoginFocusGained(evt);
            }
        });
        getContentPane().add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 263, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 630, 1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Matrícula");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        tMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tMatricula.setForeground(new java.awt.Color(51, 51, 51));
        try {
            tMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/######-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 263, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ramal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        tRamal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tRamal.setForeground(new java.awt.Color(51, 51, 51));
        try {
            tRamal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tRamal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 263, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Andar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        tSetor.setForeground(new java.awt.Color(51, 51, 51));
        tSetor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 263, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Setor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));
        getContentPane().add(tAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 100, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/solic.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       tNome.setText(s.getNome());
       tEmail.setText(s.getEmail());
       tLogin.setText(f.getLogin());
       tSenha.setText(f.getSenha());
       tMatricula.setText(s.getMatricula());
       tSetor.setText(s.getSetor());
       tRamal.setText(String.valueOf(s.getRamal()));
       tAndar.setValue(new Integer(s.getAndar()));
       
    }//GEN-LAST:event_formWindowOpened

    public void setarNovos(){
        s.setNome(tNome.getText());
        s.setEmail(tEmail.getText());
        f.setLogin(tLogin.getText());
        f.setSenha(tSenha.getText());
        s.setMatricula(tMatricula.getText());
        s.setSetor(tSetor.getText());
        s.setRamal(Integer.parseInt(tRamal.getText()));
        s.setAndar((Integer) tAndar.getValue());
        /*int andar = Integer.parseInt(tAndar.getText());
        String andar0 = String.format("%013d", andar); // 0 fill to 13 digits num
        if(andar<10)
                s.setAndar(andar0);
        else
            s.setAndar(andar);*/
    }
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        setarNovos();
        int rc=0;
        String sql="UPDATE solicitante SET matricula_Solic= '"+s.getMatricula()+"', nome_Solic= '"+s.getNome()+"', email_Solic='"+s.getEmail()+"', setor_Solic='"+s.getSetor()+"', ramal_Solic="+s.getRamal()+", andar_Solic="+s.getAndar()+" WHERE id="+f.getId();
        String sql2="UPDATE funcionario SET login= '"+f.getLogin()+"', senha= '"+f.getSenha()+"' WHERE id="+f.getId();
        Connection cn= Connecto.Conexao.getConnection();
        try{
            Statement st=cn.createStatement();
            st.executeUpdate(sql);
            st.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null,"Editado com sucesso!");
            this.dispose();
            rc=0;
            cn.close();
        }catch(SQLException  E){
            rc=111;
            JOptionPane.showMessageDialog(null,"Erro ao editar!");
            E.printStackTrace();
        }
    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
              frmSolicitante sol=new frmSolicitante();
        sol.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void tNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeFocusGained

    private void tSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSenhaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tSenhaFocusGained

    private void tLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tLoginFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tLoginFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditSol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner tAndar;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLogin;
    private javax.swing.JFormattedTextField tMatricula;
    private javax.swing.JTextField tNome;
    private javax.swing.JFormattedTextField tRamal;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTextField tSetor;
    // End of variables declaration//GEN-END:variables
}
