/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewo;

import Modelo.*;
import Viewo.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author aluno
 */
public class frmFimChamado extends javax.swing.JFrame {

    /**
     * Creates new form frmChamado
     */
    public frmFimChamado() {
        initComponents();
        this.setLocationRelativeTo(null); 
        getRootPane().setDefaultButton(btnFinalizar);  
        tDescricao.setLineWrap(true);
        tObs.setLineWrap(true);
    }
    
    Chamado c = new Chamado();
    Funcionario f = new Funcionario();
    int rc=9;

    public int setarChamado(Chamado c){
        int rc=111;
        String sql="SELECT urgencia, descricao, id_Solic, hora, date_format(data, '%d/%m/%Y') from chamado WHERE id="+c.getId();
        Connection cn=Connecto.Conexao.getConnection();
 //       System.out.println(sql);
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
               c.setUrgencia(rs.getString(1));
               c.setDescricao(rs.getString(2));
               c.setIdsolic(rs.getInt(3));
               c.setHora(rs.getString(4));
               c.setData(rs.getString(5));
               
                  cn.close();
                  rc=0;
            }
        }catch (SQLException E){
            System.out.println(E.getMessage());

        }
     
        return rc;
    }
    
    public int setarChamado2(Chamado c){
        int rc=111;
        String sql="SELECT * FROM solicitante WHERE id="+c.getIdsolic();
        Connection cn=Connecto.Conexao.getConnection();
 //       System.out.println(sql);
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
               c.setNomeSolic(rs.getString(2));
               c.setAndarSolic(rs.getInt(6));
               c.setSetorSolic(rs.getString(4));
                  cn.close();
                  rc=0;
            }
        }catch (SQLException E){
            System.out.println(E.getMessage());

        }
     
        return rc;
    }
    
    public int pegarChamado(Chamado c, Funcionario f){
        int rc=111;
        String sql="UPDATE chamado SET id_Tec= "+f.getId()+" WHERE id="+c.getId();
        String sql2="UPDATE chamado SET situacao= 'em andamento' WHERE id="+c.getId();
        Connection cn= Connecto.Conexao.getConnection();
        try{
            Statement st=cn.createStatement();
            st.executeUpdate(sql);
            st.executeUpdate(sql2);
            rc=0;
            cn.close();
        }catch(SQLException  E){
            rc=111;
            E.printStackTrace();
        }
        return rc;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tUrgencia = new javax.swing.JTextField();
        tData = new javax.swing.JTextField();
        tHora = new javax.swing.JTextField();
        tNome = new javax.swing.JTextField();
        tAndar = new javax.swing.JTextField();
        tSetor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDescricao = new javax.swing.JTextArea();
        btnFinalizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tObs = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        tCusto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Urgência");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 195, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Andar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Setor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        tUrgencia.setEditable(false);
        tUrgencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tUrgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 202, -1));

        tData.setEditable(false);
        tData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 195, 200, -1));

        tHora.setEditable(false);
        tHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, -1));

        tNome.setEditable(false);
        tNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 210, -1));

        tAndar.setEditable(false);
        tAndar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tAndar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 210, -1));

        tSetor.setEditable(false);
        tSetor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 210, -1));

        tDescricao.setEditable(false);
        tDescricao.setColumns(15);
        tDescricao.setRows(5);
        tDescricao.setWrapStyleWord(true);
        tDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jScrollPane1.setViewportView(tDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 202, 77));

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 89, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Obs final");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        tObs.setColumns(15);
        tObs.setRows(5);
        tObs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jScrollPane2.setViewportView(tObs);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 210, 41));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Custo (R$)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        tCusto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        getContentPane().add(tCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 210, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/detalhes.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setarChamado(c);
        setarChamado2(c);
        tUrgencia.setText(c.getUrgencia());
        tDescricao.setText(c.getDescricao());
        tData.setText(c.getData());
        tHora.setText(c.getHora());
        tNome.setText(c.getNomeSolic());
        tAndar.setText(String.valueOf(c.getAndarSolic()));
        tSetor.setText(String.valueOf(c.getSetorSolic()));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       frmTecnico tec=new frmTecnico();
        tec.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
                    
            //obter hora
            String formatohora = "HH:mm:ss";
            DateFormat hora = new SimpleDateFormat(formatohora);
            Date hoje = new Date();

            //obter data
            String formatodata = "yyyy-MM-dd";
            DateFormat data = new SimpleDateFormat(formatodata);

            if(tObs.getText().equals("")||tCusto.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos!");
            }else{
            
            //setando pra classe         
            c.setCusto(Double.parseDouble(tCusto.getText()));
            c.setDatafinal(data.format(hoje));
            c.setHorafinal(hora.format(hoje));
            c.setObsfinal(tObs.getText());
            
            
        int rc=111;
        String sql="UPDATE chamado SET situacao = 'finalizado', obsFinal = '"+c.getObsfinal()+"', horaFinal = '"+c.getHorafinal()+"', dataFinal = '"+c.getDatafinal()+"', custo = '"+c.getCusto()+"' WHERE chamado.id ="+c.getId();
       // sql=sql+"VALUES ("+idChamado()+", 'aberto', '"+cham.getUrgencia()+"', '"+cham.getDescricao()+"', "+func.getId()+", null, '"+hora.format(hoje)+"', '"+data.format(hoje)+"', 'Nenhuma', '00:00:00', '0000-00-00', 0);";
        Connection cn= Connecto.Conexao.getConnection();
       // System.out.print(sql);
        try{
            Statement st=cn.createStatement();
            st.executeUpdate(sql);
            rc=0;
            cn.close();
        }catch(SQLException  E){
            rc=111;
            E.printStackTrace();
        }
            
            //ctrlcham.solicitarChamado(formatohora, hora, hoje, formatodata, data);
            JOptionPane.showMessageDialog(null,"Finalizado com sucesso. Parabéns!");
            this.dispose();

            }

    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFimChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFimChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFimChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFimChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFimChamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tAndar;
    private javax.swing.JTextField tCusto;
    private javax.swing.JTextField tData;
    private javax.swing.JTextArea tDescricao;
    private javax.swing.JTextField tHora;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextArea tObs;
    private javax.swing.JTextField tSetor;
    private javax.swing.JTextField tUrgencia;
    // End of variables declaration//GEN-END:variables
}
