/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewo;

import Controllero.*;
import Modelo.*;
import Viewo.*;
import java.awt.event.KeyAdapter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/**
 *
 * @author Gabriel
 */
public class frmLogin extends javax.swing.JFrame {
    
  

    /**
     * Creates new form frmFuncionario
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null); 
        getRootPane().setDefaultButton(btnEntrar);  
        
    }
    
    
      
              
    ctrlFuncionario ctrlfunc=new ctrlFuncionario();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        tLogin = new javax.swing.JTextField();
        tSenha = new javax.swing.JPasswordField();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/entrar.png"))); // NOI18N
        btnEntrar.setAlignmentY(0.0F);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 82, 27, 26));

        tLogin.setText("Insira seu nick");
        tLogin.setToolTipText("Insira seu nick cadastrado");
        tLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tLogin.setCaretColor(new java.awt.Color(153, 153, 153));
        tLogin.setName(""); // NOI18N
        tLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tLoginFocusGained(evt);
            }
        });
        tLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tLoginMouseClicked(evt);
            }
        });
        tLogin.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tLoginInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(tLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 209, 30));
        tLogin.getAccessibleContext().setAccessibleName("");

        tSenha.setText("senha");
        tSenha.setToolTipText("Insira sua senha cadastrada");
        tSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        tSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tSenhaFocusGained(evt);
            }
        });
        tSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(tSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 209, 30));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/login.png"))); // NOI18N
        fundo.setText("jLabel4");
        fundo.setAlignmentY(0.0F);
        fundo.setName("Login"); // NOI18N
        fundo.setPreferredSize(new java.awt.Dimension(699, 359));
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
    Funcionario fun=new Funcionario();
    Solicitante sol=new Solicitante();
        if(tLogin.getText().equals("")||tSenha.getText().equals(""))
        JOptionPane.showMessageDialog(null, "Preencha os campos!");
        else
        {
            fun.setLogin(tLogin.getText());
            fun.setSenha(tSenha.getText());
            int rc;
            rc=ctrlfunc.autenticar(fun);
           // System.out.print(rc);
            if(rc==0){
                this.dispose();
                String func = fun.getPerfil();
                if (func.equalsIgnoreCase("tecnico"))
                    func = "Técnico";
                else
                    func = "Solicitante";
                JOptionPane.showMessageDialog(null,"Bem-vindo, "+func+"!", "Sucesso", JOptionPane.WARNING_MESSAGE);
                ctrlfunc.direcionar(fun, sol);
            }
            if (rc==404)
                JOptionPane.showMessageDialog(null,"Usuário incorreto!", "Falha na autenticação", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void tLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tLoginFocusGained
       if(tSenha.getText().equals(""))
            tSenha.setText("senha");
    }//GEN-LAST:event_tLoginFocusGained

    private void tSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tSenhaFocusGained
        if(tSenha.getText().equals("senha"))
            tSenha.setText("");
        if(tLogin.getText().equals(""))
            tLogin.setText("Insira seu nick");
    }//GEN-LAST:event_tSenhaFocusGained

    private void tLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tLoginMouseClicked
        if(tLogin.getText().equals("Insira seu nick"))
            tLogin.setText("");
        if(tSenha.getText().equals(""))
            tSenha.setText("senha");
    }//GEN-LAST:event_tLoginMouseClicked

    private void tSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSenhaMouseClicked
        if(tSenha.getText().equals("senha"))
            tSenha.setText("");
        if(tLogin.getText().equals(""))
            tLogin.setText("Insira seu nick");
    }//GEN-LAST:event_tSenhaMouseClicked

    private void tLoginInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tLoginInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tLoginInputMethodTextChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tLogin.setFocusable(true);
        tLogin.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel fundo;
    public javax.swing.JTextField tLogin;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables
}
