/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewo;

import java.sql.Connection;
import javax.swing.JOptionPane;
import Modelo.*;
import Controllero.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author aluno
 */
public class frmSolicitante extends javax.swing.JFrame{
    
    ctrlSolicitante ctrlsolic=new ctrlSolicitante();
    ctrlFuncionario ctrlfunc=new ctrlFuncionario();
    ctrlChamado ctrlcham=new ctrlChamado();
    int id;
    
    /**
     * Creates new form frmSolicitante
     */
    public frmSolicitante() {
        initComponents();
        this.setLocationRelativeTo(null); 
        tDesc.setLineWrap(true);
        
    }
        
    Funcionario f = new Funcionario();
    Solicitante s = new Solicitante(); 
    Chamado c = new Chamado();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSolic = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lCod = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cboUrgencia = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDesc = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();
        btnSolicitar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lSolic.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lSolic.setForeground(new java.awt.Color(255, 255, 255));
        lSolic.setText("Solicitante");
        getContentPane().add(lSolic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Novo Chamado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lCod.setForeground(java.awt.Color.gray);
        lCod.setText("COD 001");
        getContentPane().add(lCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cboUrgencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baixa", "Média", "Alta" }));
        cboUrgencia.setBorder(null);
        cboUrgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUrgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(cboUrgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Urgência");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        tDesc.setColumns(20);
        tDesc.setRows(5);
        tDesc.setWrapStyleWord(true);
        tDesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jScrollPane1.setViewportView(tDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 340, 100));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/solic.png"))); // NOI18N
        fundo.setText("jLabel1");
        fundo.setMaximumSize(new java.awt.Dimension(960, 551));
        fundo.setMinimumSize(new java.awt.Dimension(960, 551));
        fundo.setPreferredSize(new java.awt.Dimension(960, 551));
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        jMenu1.setText("Arquivo");

        jMenuItem4.setBackground(new java.awt.Color(204, 0, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/logout.png"))); // NOI18N
        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/sair.png"))); // NOI18N
        jMenuItem2.setText("Fechar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Editar");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/perfil.png"))); // NOI18N
        jMenuItem3.setText("Editar perfil");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        if(tDesc.getText().equals(""))
        JOptionPane.showMessageDialog(null, "Informe a descrição!");
        else
        {  
            //obter hora
            String formatohora = "HH:mm:ss";
            DateFormat hora = new SimpleDateFormat(formatohora);
            Date hoje = new Date();
            
            //obter data
            String formatodata = "yyyy-MM-dd";
            DateFormat data = new SimpleDateFormat(formatodata);
            
            //setar campos
            c.setDescricao(tDesc.getText());
            c.setUrgencia(String.valueOf(cboUrgencia.getSelectedItem()));
            
            cboUrgencia.setSelectedIndex(0);
            tDesc.setText("");
            ctrlcham.solicitarChamado(formatohora, hora, hoje, formatodata, data);
            JOptionPane.showMessageDialog(null," Solicitado com sucesso!");
            
            int idmore = id+1;
            lCod.setText("COD "+idmore);
            

        }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       
        tDesc.setText("");
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlcham.idChamado();
        id = c.getId();
        lCod.setText("COD "+id);
        ctrlsolic.setarDados(f);
        lSolic.setText("Bem-Vindo, "+s.getNome());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
             this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        this.dispose();
        frmLogin login=new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       frmEditSol edtsol=new frmEditSol();
        edtsol.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cboUrgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUrgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUrgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolicitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolicitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox cboUrgencia;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lCod;
    private javax.swing.JLabel lSolic;
    private javax.swing.JTextArea tDesc;
    // End of variables declaration//GEN-END:variables
}
