/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Viewo;

import javax.swing.JOptionPane;
import Modelo.*;
import Controllero.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class frmTecnico extends javax.swing.JFrame {
    
    Tecnico cli=new Tecnico();
    ctrlTecnico ctrltec=new ctrlTecnico();
    ctrlFuncionario ctrlfunc=new ctrlFuncionario();
    CadFuncionario cf = new CadFuncionario();
    public int cod;
    private List<Chamado> listaItensChamado;
    private ListSelectionModel listModelVenda;
    int linha;
    int coluna;
    int resultado;

    /**
     * Creates new form frmTecnico
     */
    public frmTecnico() {
        initComponents();
        this.setLocationRelativeTo(null);
        defineModelo1();
        defineModelo2();
    }
    
    public void fechar(){
        this.dispose();
    }

    
    private void defineModelo1(){
        listModelVenda = tabela.getSelectionModel();
        listModelVenda.addListSelectionListener(new ListSelectionListener() {
           
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    mostraDetalheChamado1();
                    frmChamado cham=new frmChamado();
                    cham.setVisible(true);
                    fechar();
                    
                }
            }
            
        });
    }
    
    
    private void mostraDetalheChamado1() {
      //  if (tabela.getColumnName(3).equals("ID")) 
         // System.out.println(tabela.getSelectedRow());
      linha = tabela.getSelectedRow();
      coluna = tabela.getSelectedColumn();
       
      String resu = String.valueOf(tabela.getValueAt(linha, 4));
     // System.out.println("oo"+resu);
        c.setId(Integer.parseInt(resu));
    }
    
    private void defineModelo2(){
        listModelVenda = tabela2.getSelectionModel();
        listModelVenda.addListSelectionListener(new ListSelectionListener() {
           
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    mostraDetalheChamado2();
                    frmFimChamado fimcham=new frmFimChamado();
                    fimcham.setVisible(true);
                    fechar();
                    
                }
            }
            
        });
    }
    
    
    private void mostraDetalheChamado2() {
      //  if (tabela.getColumnName(3).equals("ID")) 
         // System.out.println(tabela.getSelectedRow());
      linha = tabela2.getSelectedRow();
      coluna = tabela2.getSelectedColumn();
       
      String resu = String.valueOf(tabela2.getValueAt(linha, 3));
     // System.out.println("oo"+resu);
        c.setId(Integer.parseInt(resu));
    }
     
    
    Funcionario f = new Funcionario();
    Tecnico t = new Tecnico(); 
    Chamado c = new Chamado();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela2 = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lTecnico = new javax.swing.JLabel();
        lTecnico2 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(null);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lc.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 255, 255));
        lc.setText("Seus chamados em andamento");
        getContentPane().add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela2.setDragEnabled(true);
        jScrollPane1.setViewportView(tabela2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 560, 127));

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/refresh.png"))); // NOI18N
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 50, 50));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.setColumnSelectionAllowed(true);
        tabela.setDragEnabled(true);
        jScrollPane2.setViewportView(tabela);
        tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 560, 127));

        lTecnico.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lTecnico.setText("Técnico");
        getContentPane().add(lTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        lTecnico2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lTecnico2.setForeground(new java.awt.Color(255, 255, 255));
        lTecnico2.setText("Chamados abertos");
        getContentPane().add(lTecnico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/admin.jpg"))); // NOI18N
        fundo.setText("jLabel1");
        fundo.setMaximumSize(new java.awt.Dimension(960, 551));
        fundo.setMinimumSize(new java.awt.Dimension(960, 551));
        fundo.setPreferredSize(new java.awt.Dimension(960, 551));
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));

        jMenu1.setText("Arquivo");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/novo.png"))); // NOI18N
        jMenu3.setText("Novo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Técnico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Solicitante");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/logout.png"))); // NOI18N
        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/sair.png"))); // NOI18N
        jMenuItem1.setText("Fechar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exibir");

        jMenuItem6.setText("Técnicos cadastrados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Solicitantes cadastrados");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator2);

        jMenuItem8.setText("Chamados por solicitante");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Chamados por mês");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator3);

        jMenuItem10.setText("Seus chamados finalizados");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void consultar(String sql){
       frmConsultas consultas=new frmConsultas();
       consultas.setVisible(true);
       consultas.sql = sql;
   }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrltec.setarDados(f);
        lTecnico.setText("Olá, "+t.getNome());
        try{
            pegarChamadosAbertos();
            pegarChamadosAndamento();
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }       
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cf.setPerfil("tecnico");
        frmCadTec cadtec=new frmCadTec();
        cadtec.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       cf.setPerfil("solicitante");
        frmCadSol cadsol=new frmCadSol();
        cadsol.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
        frmLogin login=new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
/*      String sql="SELECT urgencia, descricao, hora, id from chamado WHERE situacao='aberto'";
        try{
            pesquisaTabela(sql);
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }   
        //frmChamado cham=new frmChamado();
        cham.dispose(); */
         
    }//GEN-LAST:event_formWindowGainedFocus

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
       
        try{
            pegarChamadosAbertos();
            pegarChamadosAndamento();
            System.out.println("atualizado");
        }catch(SQLException e) {
            System.out.println(e.getMessage());
        }   
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       consultar("SELECT nome_Tec as Nome, email_Tec as Email, id as Código FROM `tecnico` ");     
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       consultar("SELECT nome_Solic as Nome, setor_Solic as Setor, andar_Solic as Andar, ramal_Solic as Ramal, id as Código FROM `solicitante` "); 
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       int cod_solic = Integer.parseInt(JOptionPane.showInputDialog(null, "Insira o código do solicitante"));
        consultar("SELECT urgencia as Urgência, descricao as Descrição, hora as Hora, date_format(data, '%d/%m/%Y') AS Data, id as Código from chamado WHERE id_Solic ="+cod_solic);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
              int mes = Integer.parseInt(JOptionPane.showInputDialog(null, "Insira um mês"));
        consultar("SELECT c.situacao as Situação, c.urgencia as Urgência, c.descricao as Descrição, t.nome_Tec as Técnico, s.setor_Solic as Setor, c.hora as Hora, date_format(c.data, '%d/%m/%Y') AS Data FROM chamado c, tecnico t, solicitante s WHERE c.id_Tec = t.id AND s.id = c.id_Solic AND month(data) ="+mes);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        consultar("SELECT urgencia as Urgência, descricao as Descrição, horaFinal as Hora, date_format(dataFinal, '%d/%m/%Y') AS Data, obsFinal as Observação, custo as Custo, chamado.id as Código from chamado WHERE situacao = 'finalizado' AND id_Tec = '"+f.getId()+"'");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTecnico().setVisible(true);
            }
        });
    }

    public void pegarChamadosAbertos() throws SQLException{
        String sql="SELECT urgencia, descricao, hora, date_format(data, '%d/%m/%Y'), id from chamado WHERE situacao='aberto'";
                   Connection conexao=Connecto.Conexao.getConnection();
                   Statement st=conexao.createStatement();
                   DefaultTableModel aModel=(DefaultTableModel)tabela.getModel();
                  aModel.setRowCount(0); //posiciona na linha zero
                   aModel.setColumnCount(0); //posiciona na coluna zero
                   tabela.setRowHeight(30); //determina tam de coluna em 30
                   ResultSet rs=st.executeQuery(sql);
                   //manipula dado resultante do sql
                   ResultSetMetaData rsmd=rs.getMetaData();
                   //pega as caracteristicas dos campos
                   int colno=rsmd.getColumnCount();
                   //pega a quantidade de colunas resultantes do sql
                   
                 /*  String nome="";
                   for(int j=1; j<=colno; j++){
                       nome=rsmd.getColumnName(j); //pega o nome da coluna
                     //  System.out.println(nome);
                    aModel.addColumn(nome);
                   }*/
                   
                   aModel.addColumn("Urgência");
                   aModel.addColumn("Descrição");
                   aModel.addColumn("Hora");
                   aModel.addColumn("Data");
                   aModel.addColumn("Código");
                   
                   while(rs.next()){
                       Object[] object=new Object[colno];
                       for(int i=0; i<colno; i++){
                           object[i]=rs.getObject(i+1);
                        //   System.out.println(object[i]);
                       }
                       aModel.addRow(object);
                   }
                   tabela.setModel(aModel); //associao objeto virtual amodel a tabela real
                }
    
    public void pegarChamadosAndamento() throws SQLException{
        String sql="SELECT s.setor_Solic, c.descricao, c.hora, c.id\n" +
        "FROM chamado c, tecnico t, solicitante s\n" +
        "WHERE c.id_Tec = t.id\n" +
        "AND situacao = 'em andamento'\n" +
        "AND s.id = c.id_Solic\n" +   
        "AND t.nome_Tec = '"+t.getNome()+"'\n" +
        "ORDER BY c.id ASC ";
                   Connection conexao=Connecto.Conexao.getConnection();
                   Statement st=conexao.createStatement();
                   DefaultTableModel aModel=(DefaultTableModel)tabela2.getModel();
                  aModel.setRowCount(0); //posiciona na linha zero
                   aModel.setColumnCount(0); //posiciona na coluna zero
                   tabela2.setRowHeight(30); //determina tam de coluna em 30
                   ResultSet rs=st.executeQuery(sql);
                   //manipula dado resultante do sql
                   ResultSetMetaData rsmd=rs.getMetaData();
                   //pega as caracteristicas dos campos
                   int colno=rsmd.getColumnCount();
                   //pega a quantidade de colunas resultantes do sql
                   
                 /*  String nome="";
                   for(int j=1; j<=colno; j++){
                       nome=rsmd.getColumnName(j); //pega o nome da coluna
                     //  System.out.println(nome);
                    aModel.addColumn(nome);
                   }*/
                   
                   aModel.addColumn("Setor");
                   aModel.addColumn("Descrição");
                   aModel.addColumn("Hora");
                   aModel.addColumn("Código");
                   
                   while(rs.next()){
                       Object[] object=new Object[colno];
                       for(int i=0; i<colno; i++){
                           object[i]=rs.getObject(i+1);
                        //   System.out.println(object[i]);
                       }
                       aModel.addRow(object);
                   }
                   tabela2.setModel(aModel); //associao objeto virtual amodel a tabela real
                }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel fundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lTecnico;
    private javax.swing.JLabel lTecnico2;
    private javax.swing.JLabel lc;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabela2;
    // End of variables declaration//GEN-END:variables
}
